# Generated by Django 5.0.6 on 2024-07-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agua", "0002_tabelaagua"),
    ]

    operations = [
        migrations.AddField(
            model_name="tabelaagua",
            name="Xileno",
            field=models.FloatField(null=True, verbose_name="Xileno - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="_1_1_dicloroeteno",
            field=models.FloatField(null=True, verbose_name="1,1-Dicloroeteno - mg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="_1_2_dicloroetano",
            field=models.FloatField(null=True, verbose_name="1,2-Dicloroetano - mg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="_2_4_5_t",
            field=models.FloatField(null=True, verbose_name="2,4,5-T - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="_2_4_5_tp",
            field=models.FloatField(null=True, verbose_name="2,4,5-TP - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="_2_4_6_triclorofenol",
            field=models.FloatField(
                null=True, verbose_name="2 , 4 , 6 - Triclorofenol   - mg/L"
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="_2_4_d",
            field=models.FloatField(null=True, verbose_name="2,4-D - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="_2_4_diclorofenol",
            field=models.FloatField(null=True, verbose_name="2,4-Diclorofenol - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="_2_clorofenol",
            field=models.FloatField(null=True, verbose_name="2-Clorofenol - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="_3_3_diclorobenzidina",
            field=models.FloatField(
                null=True, verbose_name="3,3-Diclorobenzidina - µg/L"
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="acrilamida",
            field=models.FloatField(null=True, verbose_name="Acrilamida - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="alacloro",
            field=models.FloatField(null=True, verbose_name="Alacloro - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="aldrin_dieldrin",
            field=models.FloatField(null=True, verbose_name="Aldrin + Dieldrin - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="aluminio_dissolvido",
            field=models.FloatField(
                null=True, verbose_name="Alumínio dissolvido - mg/L Al"
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="antimonio",
            field=models.FloatField(null=True, verbose_name="Antimônio - mg/L Sb"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="atrazina",
            field=models.FloatField(null=True, verbose_name="Atrazina - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="bario_total",
            field=models.FloatField(null=True, verbose_name="Bário total - mg/L Ba"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="benzeno",
            field=models.FloatField(null=True, verbose_name="Benzeno - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="benzidina",
            field=models.FloatField(null=True, verbose_name="Benzidina - mg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="benzo_antraceno",
            field=models.FloatField(
                null=True, verbose_name="Benzo (a) antraceno - µg/L"
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="benzo_b_fluoranteno",
            field=models.FloatField(
                null=True, verbose_name="Benzo(b) fluoranteno - µg/L"
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="benzo_k_fluoranteno",
            field=models.FloatField(
                null=True, verbose_name="Benzo(k) fluoranteno - µg/L"
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="benzo_pireno",
            field=models.FloatField(null=True, verbose_name=" Benzo (a) pireno - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="berilio_total",
            field=models.FloatField(null=True, verbose_name="Berílio total - mg/L Be"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="boro_total",
            field=models.FloatField(null=True, verbose_name="Boro total - mg/L B"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="cadmio_total",
            field=models.FloatField(null=True, verbose_name="Cádmio total  - mg/L Cd"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="carbaril",
            field=models.FloatField(null=True, verbose_name="Carbaril - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="chumbo_total",
            field=models.FloatField(null=True, verbose_name="Chumbo total  - mg/L Pb"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="cianeto_livre",
            field=models.FloatField(null=True, verbose_name="Cianeto livre -  mg/L CN"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="clordano_cis_trans",
            field=models.FloatField(
                null=True, verbose_name="Clordano (cis + trans) - µg/L"
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="cloreto_total",
            field=models.FloatField(null=True, verbose_name="Cloreto total - mg/L Cl"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="cloro_residual_total_combinado_livre",
            field=models.FloatField(
                null=True,
                verbose_name="Cloro residual total (combinado + livre) -  mg/L Cl",
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="cobalto_total",
            field=models.FloatField(null=True, verbose_name="Cobalto total - mg/L Co"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="cobre_dissolvido",
            field=models.FloatField(
                null=True, verbose_name="Cobre dissolvido - mg/L Cu"
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="corofila_a",
            field=models.FloatField(null=True, verbose_name="Clorofila a - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="criseno",
            field=models.FloatField(null=True, verbose_name="Criseno - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="cromo_total",
            field=models.FloatField(null=True, verbose_name="Cromo total - mg/L Cr"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="ddt_p_p_ddt_p_p_dde_p_p_ddd",
            field=models.FloatField(
                null=True, verbose_name="DDT (p,p'-DDT + p,p'-DDE + p,p'-DDD) - µg/L"
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="demeton_demeton_o_demeton_s",
            field=models.FloatField(
                null=True, verbose_name="Demeton (Demeton-O + Demeton-S) - µg/L"
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="densidade_de_cianobactérias",
            field=models.FloatField(
                null=True, verbose_name="Densidade de cianobactérias  - cel/mL"
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="dibenzo_antraceno",
            field=models.FloatField(
                null=True, verbose_name="Dibenzo (a,h) antraceno - µg/L"
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="diclorometano",
            field=models.FloatField(null=True, verbose_name="Diclorometano - mg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="dodecacloro_pentaciclodecano",
            field=models.FloatField(
                null=True, verbose_name="Dodecacloro pentaciclodecano - µg/L"
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="eilbenzeno",
            field=models.FloatField(null=True, verbose_name="Etilbenzeno - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="endossulfan_a_b_sulfato",
            field=models.FloatField(
                null=True, verbose_name="Endossulfan (a + b + sulfato) - µg/L"
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="endrin",
            field=models.FloatField(null=True, verbose_name="Endrin - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="estireno",
            field=models.FloatField(null=True, verbose_name="Estireno - mg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="fenois_totais_4_aminoantipirina",
            field=models.FloatField(
                null=True,
                verbose_name="EFenóis totais (substâncias que reagem com 4-aminoantipirina) - mg/L C6H5OH",
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="ferro_dissolvido",
            field=models.FloatField(
                null=True, verbose_name="Ferro dissolvido - mg/L Fe"
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="fluoreto_total",
            field=models.FloatField(null=True, verbose_name="Fluoreto total-  mg/L F"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="fosforo_total_ambiente_intermediario",
            field=models.FloatField(
                null=True,
                verbose_name="Fósforo total (ambiente intermediário, com tempo de residência entre 2 e 40 dias, e tributários diretos de ambiente lênt.) - mg/L P",
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="fosforo_total_ambiente_lentico",
            field=models.FloatField(
                null=True, verbose_name="Fósforo total (ambiente lêntico) - mg/L P"
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="fosforo_total_ambiente_lotico",
            field=models.FloatField(
                null=True,
                verbose_name="Fósforo  total  (amb.  lótico  e tributários de ambientes intermediários) - mg/L P",
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="glifosato",
            field=models.FloatField(null=True, verbose_name="Glifosato - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="gution",
            field=models.FloatField(null=True, verbose_name="Gution - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="heptacloro_epoxido_heptacloro",
            field=models.FloatField(
                null=True, verbose_name="Heptacloro epóxido + Heptacloro - µg/L"
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="hexaclorobenzeno",
            field=models.FloatField(null=True, verbose_name="Hexaclorobenzeno - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="indeno_1_2_3_cd_pireno",
            field=models.FloatField(
                null=True, verbose_name="Indeno (1,2,3-cd) pireno - µg/L"
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="lindano_g_HCH",
            field=models.FloatField(null=True, verbose_name="Lindano (g-HCH) - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="litio_total",
            field=models.FloatField(null=True, verbose_name="Lítio total - mg/L Li"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="malation",
            field=models.FloatField(null=True, verbose_name="Malation - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="manganes_total",
            field=models.FloatField(null=True, verbose_name="Manganês total - mg/L Mn"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="mercurio_total",
            field=models.FloatField(null=True, verbose_name="Mercúrio total - mg/L Hg"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="metolacloro",
            field=models.FloatField(null=True, verbose_name="Metolacloro - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="metoxicloro",
            field=models.FloatField(null=True, verbose_name="metoxicloro - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="monoclorobenzeno",
            field=models.FloatField(null=True, verbose_name="monoclorobenzeno - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="niqueltotal",
            field=models.FloatField(null=True, verbose_name="Níquel total -  mg/L Ni"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="nitrato",
            field=models.FloatField(null=True, verbose_name="Nitrato - mg/L N"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="nitrito",
            field=models.FloatField(null=True, verbose_name="Nitrito - mg/L N"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="nitrogenio_amoniacal_total",
            field=models.FloatField(
                null=True, verbose_name="Nitrogênio amoniacal total - mg/L N"
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="paration",
            field=models.FloatField(null=True, verbose_name="Paration - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="pcbs_ifenilas_policloradas",
            field=models.FloatField(
                null=True, verbose_name="PCBs - Bifenilas policloradas  - µg/L"
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="pentaclorofenol",
            field=models.FloatField(null=True, verbose_name="Pentaclorofenol - mg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="polifosfatos",
            field=models.FloatField(
                null=True,
                verbose_name="Polifosfatos (determinado pela diferença entre fósforo ácido hidrolisável total e fósforo reativo total)",
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="prata_total",
            field=models.FloatField(null=True, verbose_name="Prata total - mg/L Ag"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="selenio_total",
            field=models.FloatField(null=True, verbose_name="Selênio total - mg/L Se"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="simazina",
            field=models.FloatField(null=True, verbose_name="Simazina - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="solidos_dissolvidos_totais",
            field=models.FloatField(
                null=True, verbose_name="Sólidos dissolvidos totais -  mg/L"
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="substancias_tensoativas",
            field=models.FloatField(
                null=True,
                verbose_name="Substâncias tensoativas que reagem com o azul de metileno - mg/L LAS",
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="sulfato_total",
            field=models.FloatField(null=True, verbose_name="Sulfato total - mg/L SO4"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="sulfeto_H2S_nao_dissociado",
            field=models.FloatField(
                null=True, verbose_name="Sulfeto (H2S não dissociado) -  mg/L S"
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="taliototal",
            field=models.FloatField(null=True, verbose_name="Tálio total - mg/L Tl "),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="tetracloreto_carbono",
            field=models.FloatField(
                null=True, verbose_name="Tetracloreto de carbono - mg/L"
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="tetracloroeteno",
            field=models.FloatField(null=True, verbose_name="Tetracloroeteno - mg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="tolueno",
            field=models.FloatField(null=True, verbose_name="Tolueno - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="toxafeno",
            field=models.FloatField(null=True, verbose_name="Toxafeno - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="tributilestanho",
            field=models.FloatField(
                null=True, verbose_name="Tributilestanho - µg/L TBT"
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="triclorobenzeno",
            field=models.FloatField(
                null=True,
                verbose_name="Triclorobenzeno  (1,2,3-TCB  +  1,2,4-TCB) - mg/L",
            ),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="tricloroeteno",
            field=models.FloatField(null=True, verbose_name="Tricloroeteno - mg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="trifluralina",
            field=models.FloatField(null=True, verbose_name="Trifluralina - µg/L"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="uranio_total",
            field=models.FloatField(null=True, verbose_name="Urânio total -  mg/L U"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="vanadio_total",
            field=models.FloatField(null=True, verbose_name="Vanádio total -  mg/L V"),
        ),
        migrations.AddField(
            model_name="tabelaagua",
            name="zinco_total",
            field=models.FloatField(null=True, verbose_name="Zinco total -  mg/L Zn"),
        ),
    ]
